# Generated by Django 4.0.6 on 2022-10-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.AutoField(primary_key=True, serialize=False)),
                ('movie_name', models.CharField(max_length=50)),
                ('movie_duration', models.CharField(default='2hr 45m', max_length=300)),
                ('movie_rdate', models.CharField(default='null', max_length=50)),
                ('movie_poster', models.ImageField(default='static/images/movieCardPosters/boys3.jpg', upload_to='')),
                ('movie_genre', models.CharField(default='Action | Historical ', max_length=50)),
            ],
        ),
    ]
