# Generated by Django 4.0.6 on 2022-10-11 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookseats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CinemaTheater',
            fields=[
                ('cinema', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='cinema_manager', max_length=30)),
                ('cinema_name', models.CharField(max_length=50)),
                ('phoneno', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('shows', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=100)),
                ('date', models.CharField(default='', max_length=15)),
                ('price', models.IntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemaTheater', to='bookseats.cinematheater')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_show', to='bookseats.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('useat', models.CharField(max_length=100)),
                ('shows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookseats.shows')),
            ],
        ),
    ]
