# Generated by Django 4.0.6 on 2022-10-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookseats', '0003_remove_cinematheater_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movieid',
            new_name='Mid',
        ),
    ]
