# Generated by Django 4.0.6 on 2022-10-11 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookseats', '0004_rename_movieid_movie_mid'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_banner',
            field=models.ImageField(default='media/MovieCardPosters/boys3.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.ImageField(default='media/MovieCardPosters/boys3.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='shows',
            name='cinema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_show', to='bookseats.cinematheater'),
        ),
    ]
