# Generated by Django 4.0.6 on 2022-10-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookseats', '0005_movie_movie_banner_alter_movie_movie_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_banner',
            field=models.ImageField(default='media/MovieCardPosters/Shivpratap.jpg', upload_to=''),
        ),
    ]
